viento_sur_homepage:
    resource: "@VientoSurAppAppBundle/Controller/IndexController.php"
    type:     annotation

viento_sur_hotel:
    resource: "@VientoSurAppAppBundle/Controller/HotelController.php"
    type:     annotation