viento_sur_homepage:
    resource: "@VientoSurAppAppBundle/Controller/IndexController.php"
    type:     annotation

viento_sur_hotel:
    resource: "@VientoSurAppAppBundle/Controller/HotelController.php"
    type:     annotation

viento_sur_flight:
    resource: "@VientoSurAppAppBundle/Controller/FlightController.php"
    type:     annotation

viento_sur_test:
    resource: "@VientoSurAppAppBundle/Controller/TestController.php"
    type:     annotation