viento_sur_homepage:
    resource: "@VientoSurAppAppBundle/Controller/IndexController.php"
    type:     annotation

viento_sur_hotel:
    resource: "@VientoSurAppAppBundle/Controller/HotelController.php"
    type:     annotation

viento_sur_flight:
    resource: "@VientoSurAppAppBundle/Controller/FlightController.php"
    type:     annotation

viento_sur_test:
    resource: "@VientoSurAppAppBundle/Controller/TestController.php"
    type:     annotation

viento_sur_admin:
    resource: "@VientoSurAppAppBundle/Controller/DashboardController.php"
    type:     annotation

viento_sur_user:
    resource: "@VientoSurAppAppBundle/Controller/UserController.php"
    type:     annotation

viento_sur_promotions:
    resource: "@VientoSurAppAppBundle/Controller/PromotionsController.php"
    type:     annotation

viento_sur_promotion_sections:
    resource: "@VientoSurAppAppBundle/Controller/PromotionSectionsController.php"
    type:     annotation