viento_sur_homepage:
    resource: "@VientoSurAppAppBundle/Controller/IndexController.php"
    type:     annotation

viento_sur_hotel:
    resource: "@VientoSurAppAppBundle/Controller/HotelController.php"
    type:     annotation

viento_sur_flight:
    resource: "@VientoSurAppAppBundle/Controller/FlightController.php"
    type:     annotation

viento_sur_test:
    resource: "@VientoSurAppAppBundle/Controller/TestController.php"
    type:     annotation

viento_sur_admin:
    resource: "@VientoSurAppAppBundle/Controller/Dashboard/DashboardController.php"
    type:     annotation

viento_sur_user:
    resource: "@VientoSurAppAppBundle/Controller/UserController.php"
    type:     annotation

viento_sur_promotions:
    resource: "@VientoSurAppAppBundle/Controller/Dashboard/PromotionsController.php"
    type:     annotation

viento_sur_promotion_sections:
    resource: "@VientoSurAppAppBundle/Controller/Dashboard/PromotionSectionsController.php"
    type:     annotation

viento_sur_dashboard_hotel:
    resource: "@VientoSurAppAppBundle/Controller/Dashboard/HotelController.php"
    type:     annotation

viento_sur_dashboard_picture:
    resource: "@VientoSurAppAppBundle/Controller/Dashboard/PictureController.php"
    type:     annotation

viento_sur_dashboard_rooms:
    resource: "@VientoSurAppAppBundle/Controller/Dashboard/RoomsController.php"
    type:     annotation