# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    form_helper:
        class: VientoSur\App\AppBundle\Services\FormHelper
        arguments:
            "dp": "@despegar"
    despegar:
        class: VientoSur\App\AppBundle\Services\Despegar
        arguments: []
    email.service:
        class: VientoSur\App\AppBundle\Services\Email
        arguments: [@mailer,@templating]