# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    form_helper:
        class: VientoSur\App\AppBundle\Services\FormHelper
        arguments:
            "dp": "@despegar"
    flights_service:
        class: VientoSur\App\AppBundle\Services\Flights
        arguments:
            "dp": "@despegar"
            "email": "@email.service"
            "entityManager": "@doctrine.orm.entity_manager"
            "agentCode": "%agent_code%"
            "logger": "@logger"
            "knp_snappy": "@knp_snappy.pdf"
            "templating": "@templating"
            "container": "@service_container"
    hotel_service:
        class: VientoSur\App\AppBundle\Services\Hotel
        arguments:
            "dp": "@despegar"
            "email": "@email.service"
            "entityManager": "@doctrine.orm.entity_manager"
            "logger": "@logger"
            "form": "@form_helper"
            "isTest": "%is_test%"
            "session": "@session"
            "knp_snappy": "@knp_snappy.pdf"
            "templating": "@templating"

    despegar:
        class: VientoSur\App\AppBundle\Services\Despegar
        arguments: [@guzzle.client.api_vault,@guzzle.client.api_despegar,"%api_key%", "%api_key_test%", "%service_version%", "%service_url%", "%service_vault_url%", "%service_vault_url_test%", "%is_test%", "@Session"]
    email.service:
        class: VientoSur\App\AppBundle\Services\Email
        arguments: [@mailer,@templating, @service_container, @session]
    booking_helper:
        class: VientoSur\App\AppBundle\Services\BookingHelper
    app.card:
        class: VientoSur\App\AppBundle\Utils\Card
    app.bank:
        class: VientoSur\App\AppBundle\Utils\Bank

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.text:
         class: Twig_Extensions_Extension_Text
         tags:
             - { name: twig.extension }