api_autocomplete:
    type: rest
    resource: VientoSurApiBundle:Autocomplete

api_hotel:
    type: rest
    resource: VientoSurApiBundle:Hotel

api_payment:
    type: rest
    resource: VientoSurApiBundle:Payment